// Code generated by MockGen. DO NOT EDIT.
// Source: core.go
//
// Generated by this command:
//
//	mockgen -source=core.go -destination=mocks/mock_core.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/thetonymaster/mentat/internal/core"
	trace "github.com/thetonymaster/mentat/internal/trace"
	gomock "go.uber.org/mock/gomock"
)

// MockComparator is a mock of Comparator interface.
type MockComparator struct {
	ctrl     *gomock.Controller
	recorder *MockComparatorMockRecorder
	isgomock struct{}
}

// MockComparatorMockRecorder is the mock recorder for MockComparator.
type MockComparatorMockRecorder struct {
	mock *MockComparator
}

// NewMockComparator creates a new mock instance.
func NewMockComparator(ctrl *gomock.Controller) *MockComparator {
	mock := &MockComparator{ctrl: ctrl}
	mock.recorder = &MockComparatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComparator) EXPECT() *MockComparatorMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockComparator) Compare(ctx context.Context, ev core.Evidence, e core.Expectation) (core.Verdict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", ctx, ev, e)
	ret0, _ := ret[0].(core.Verdict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockComparatorMockRecorder) Compare(ctx, ev, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockComparator)(nil).Compare), ctx, ev, e)
}

// Name mocks base method.
func (m *MockComparator) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockComparatorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockComparator)(nil).Name))
}

// MockAggregateComparator is a mock of AggregateComparator interface.
type MockAggregateComparator struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateComparatorMockRecorder
	isgomock struct{}
}

// MockAggregateComparatorMockRecorder is the mock recorder for MockAggregateComparator.
type MockAggregateComparatorMockRecorder struct {
	mock *MockAggregateComparator
}

// NewMockAggregateComparator creates a new mock instance.
func NewMockAggregateComparator(ctrl *gomock.Controller) *MockAggregateComparator {
	mock := &MockAggregateComparator{ctrl: ctrl}
	mock.recorder = &MockAggregateComparatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateComparator) EXPECT() *MockAggregateComparatorMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockAggregateComparator) Aggregate(ctx context.Context, evs []core.Evidence, e core.Expectation) (core.Verdict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, evs, e)
	ret0, _ := ret[0].(core.Verdict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockAggregateComparatorMockRecorder) Aggregate(ctx, evs, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockAggregateComparator)(nil).Aggregate), ctx, evs, e)
}

// Name mocks base method.
func (m *MockAggregateComparator) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAggregateComparatorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAggregateComparator)(nil).Name))
}

// MockExpectationParser is a mock of ExpectationParser interface.
type MockExpectationParser struct {
	ctrl     *gomock.Controller
	recorder *MockExpectationParserMockRecorder
	isgomock struct{}
}

// MockExpectationParserMockRecorder is the mock recorder for MockExpectationParser.
type MockExpectationParserMockRecorder struct {
	mock *MockExpectationParser
}

// NewMockExpectationParser creates a new mock instance.
func NewMockExpectationParser(ctrl *gomock.Controller) *MockExpectationParser {
	mock := &MockExpectationParser{ctrl: ctrl}
	mock.recorder = &MockExpectationParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpectationParser) EXPECT() *MockExpectationParserMockRecorder {
	return m.recorder
}

// ParseExpectation mocks base method.
func (m *MockExpectationParser) ParseExpectation(text string) (core.Expectation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseExpectation", text)
	ret0, _ := ret[0].(core.Expectation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseExpectation indicates an expected call of ParseExpectation.
func (mr *MockExpectationParserMockRecorder) ParseExpectation(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseExpectation", reflect.TypeOf((*MockExpectationParser)(nil).ParseExpectation), text)
}

// MockPhraseContributor is a mock of PhraseContributor interface.
type MockPhraseContributor struct {
	ctrl     *gomock.Controller
	recorder *MockPhraseContributorMockRecorder
	isgomock struct{}
}

// MockPhraseContributorMockRecorder is the mock recorder for MockPhraseContributor.
type MockPhraseContributorMockRecorder struct {
	mock *MockPhraseContributor
}

// NewMockPhraseContributor creates a new mock instance.
func NewMockPhraseContributor(ctrl *gomock.Controller) *MockPhraseContributor {
	mock := &MockPhraseContributor{ctrl: ctrl}
	mock.recorder = &MockPhraseContributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhraseContributor) EXPECT() *MockPhraseContributorMockRecorder {
	return m.recorder
}

// ContributedPhrases mocks base method.
func (m *MockPhraseContributor) ContributedPhrases() []core.ContributedPhrase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContributedPhrases")
	ret0, _ := ret[0].([]core.ContributedPhrase)
	return ret0
}

// ContributedPhrases indicates an expected call of ContributedPhrases.
func (mr *MockPhraseContributorMockRecorder) ContributedPhrases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContributedPhrases", reflect.TypeOf((*MockPhraseContributor)(nil).ContributedPhrases))
}

// MockCaptureParser is a mock of CaptureParser interface.
type MockCaptureParser struct {
	ctrl     *gomock.Controller
	recorder *MockCaptureParserMockRecorder
	isgomock struct{}
}

// MockCaptureParserMockRecorder is the mock recorder for MockCaptureParser.
type MockCaptureParserMockRecorder struct {
	mock *MockCaptureParser
}

// NewMockCaptureParser creates a new mock instance.
func NewMockCaptureParser(ctrl *gomock.Controller) *MockCaptureParser {
	mock := &MockCaptureParser{ctrl: ctrl}
	mock.recorder = &MockCaptureParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptureParser) EXPECT() *MockCaptureParserMockRecorder {
	return m.recorder
}

// ParseCaptures mocks base method.
func (m *MockCaptureParser) ParseCaptures(caps []string) (core.Expectation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseCaptures", caps)
	ret0, _ := ret[0].(core.Expectation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseCaptures indicates an expected call of ParseCaptures.
func (mr *MockCaptureParserMockRecorder) ParseCaptures(caps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseCaptures", reflect.TypeOf((*MockCaptureParser)(nil).ParseCaptures), caps)
}

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockDriver) Run(ctx context.Context, spec core.RunSpec) (core.RunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, spec)
	ret0, _ := ret[0].(core.RunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockDriverMockRecorder) Run(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDriver)(nil).Run), ctx, spec)
}

// MockTraceStore is a mock of TraceStore interface.
type MockTraceStore struct {
	ctrl     *gomock.Controller
	recorder *MockTraceStoreMockRecorder
	isgomock struct{}
}

// MockTraceStoreMockRecorder is the mock recorder for MockTraceStore.
type MockTraceStoreMockRecorder struct {
	mock *MockTraceStore
}

// NewMockTraceStore creates a new mock instance.
func NewMockTraceStore(ctrl *gomock.Controller) *MockTraceStore {
	mock := &MockTraceStore{ctrl: ctrl}
	mock.recorder = &MockTraceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTraceStore) EXPECT() *MockTraceStoreMockRecorder {
	return m.recorder
}

// Caps mocks base method.
func (m *MockTraceStore) Caps() core.StoreCaps {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Caps")
	ret0, _ := ret[0].(core.StoreCaps)
	return ret0
}

// Caps indicates an expected call of Caps.
func (mr *MockTraceStoreMockRecorder) Caps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Caps", reflect.TypeOf((*MockTraceStore)(nil).Caps))
}

// DecodePayload mocks base method.
func (m *MockTraceStore) DecodePayload(id string, payload []byte) (*trace.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodePayload", id, payload)
	ret0, _ := ret[0].(*trace.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodePayload indicates an expected call of DecodePayload.
func (mr *MockTraceStoreMockRecorder) DecodePayload(id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodePayload", reflect.TypeOf((*MockTraceStore)(nil).DecodePayload), id, payload)
}

// FetchPayload mocks base method.
func (m *MockTraceStore) FetchPayload(ctx context.Context, id string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPayload", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPayload indicates an expected call of FetchPayload.
func (mr *MockTraceStoreMockRecorder) FetchPayload(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPayload", reflect.TypeOf((*MockTraceStore)(nil).FetchPayload), ctx, id)
}

// Query mocks base method.
func (m *MockTraceStore) Query(ctx context.Context, q core.TraceQuery) ([]core.TraceRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]core.TraceRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockTraceStoreMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockTraceStore)(nil).Query), ctx, q)
}

// MockCorrelator is a mock of Correlator interface.
type MockCorrelator struct {
	ctrl     *gomock.Controller
	recorder *MockCorrelatorMockRecorder
	isgomock struct{}
}

// MockCorrelatorMockRecorder is the mock recorder for MockCorrelator.
type MockCorrelatorMockRecorder struct {
	mock *MockCorrelator
}

// NewMockCorrelator creates a new mock instance.
func NewMockCorrelator(ctrl *gomock.Controller) *MockCorrelator {
	mock := &MockCorrelator{ctrl: ctrl}
	mock.recorder = &MockCorrelatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCorrelator) EXPECT() *MockCorrelatorMockRecorder {
	return m.recorder
}

// Inject mocks base method.
func (m *MockCorrelator) Inject(ctx context.Context, spec *core.RunSpec) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inject", ctx, spec)
	ret0, _ := ret[0].(string)
	return ret0
}

// Inject indicates an expected call of Inject.
func (mr *MockCorrelatorMockRecorder) Inject(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inject", reflect.TypeOf((*MockCorrelator)(nil).Inject), ctx, spec)
}

// Resolve mocks base method.
func (m *MockCorrelator) Resolve(ctx context.Context, store core.TraceStore, req core.ResolveRequest) (*trace.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, store, req)
	ret0, _ := ret[0].(*trace.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockCorrelatorMockRecorder) Resolve(ctx, store, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockCorrelator)(nil).Resolve), ctx, store, req)
}

// ResolveComplete mocks base method.
func (m *MockCorrelator) ResolveComplete(ctx context.Context, store core.TraceStore, runID string) (*trace.Trace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveComplete", ctx, store, runID)
	ret0, _ := ret[0].(*trace.Trace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveComplete indicates an expected call of ResolveComplete.
func (mr *MockCorrelatorMockRecorder) ResolveComplete(ctx, store, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveComplete", reflect.TypeOf((*MockCorrelator)(nil).ResolveComplete), ctx, store, runID)
}

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
	isgomock struct{}
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// Match mocks base method.
func (m *MockMatcher) Match(ctx context.Context, ev core.Evidence, want, target string) (core.Verdict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", ctx, ev, want, target)
	ret0, _ := ret[0].(core.Verdict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Match indicates an expected call of Match.
func (mr *MockMatcherMockRecorder) Match(ctx, ev, want, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockMatcher)(nil).Match), ctx, ev, want, target)
}

// Name mocks base method.
func (m *MockMatcher) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMatcherMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMatcher)(nil).Name))
}

// MockJudge is a mock of Judge interface.
type MockJudge struct {
	ctrl     *gomock.Controller
	recorder *MockJudgeMockRecorder
	isgomock struct{}
}

// MockJudgeMockRecorder is the mock recorder for MockJudge.
type MockJudgeMockRecorder struct {
	mock *MockJudge
}

// NewMockJudge creates a new mock instance.
func NewMockJudge(ctrl *gomock.Controller) *MockJudge {
	mock := &MockJudge{ctrl: ctrl}
	mock.recorder = &MockJudgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudge) EXPECT() *MockJudgeMockRecorder {
	return m.recorder
}

// Judge mocks base method.
func (m *MockJudge) Judge(ctx context.Context, req core.JudgeRequest) (core.JudgeVerdict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Judge", ctx, req)
	ret0, _ := ret[0].(core.JudgeVerdict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Judge indicates an expected call of Judge.
func (mr *MockJudgeMockRecorder) Judge(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Judge", reflect.TypeOf((*MockJudge)(nil).Judge), ctx, req)
}
