package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/thetonymaster/mentat/internal/steps"
)

// TestStepsCmdMarkdownMatchesCommittedDoc is the regeneration-clean gate (US1,
// SC): the markdown the `steps` command emits must equal the committed
// docs/steps.md byte-for-byte, so `go generate ./...` is the only way the file
// changes and it can never silently drift from the metadata table + grammar.
func TestStepsCmdMarkdownMatchesCommittedDoc(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	if err := stepsCmd([]string{"--format", "md"}, &buf); err != nil {
		t.Fatalf("stepsCmd --format md: %v", err)
	}
	got := buf.String()

	path := filepath.Join("..", "..", "docs", "steps.md")
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if got != string(want) {
		t.Errorf("docs/steps.md is stale (%d generated bytes vs %d committed); run `go generate ./...`", len(got), len(want))
	}
}

// TestStepsCmdFormats pins the rendered surface across formats: the default is
// text; both formats group every step and carry the cross-cutting grammar
// (selectors, quantifiers, ordinals, CEL variables) grounded in the code; an
// unknown format is a hard error naming the offending value.
func TestStepsCmdFormats(t *testing.T) {
	t.Parallel()

	// Grammar anchors pulled from the actual definitions: a selector key=value form
	// (shape_selector.go), a canonical span.status value (trace.go), an ordinal and a
	// quantifier word (result_span.go / parseSpanSpec / step patterns), a single-run
	// CEL var (cel.go), and the aggregate binding (aggregate.go).
	grammarAnchors := []string{
		"Selectors", "Quantifiers", "Ordinals", "CEL",
		"service.name=billing", "span.status", "Error",
		"every", "any", "at least", "exactly",
		"tokens", "cost", "runs",
	}
	groups := []string{"Drive", "Sequence", "Budgets", "Result", "Aggregate / CEL", "Shape"}

	tests := []struct {
		name    string
		args    []string
		wantErr bool
		// substrings the output must contain on the success path.
		want []string
	}{
		{
			name: "default format is text",
			args: nil,
			want: append(append([]string{}, groups...), grammarAnchors...),
		},
		{
			name: "explicit text",
			args: []string{"--format", "text"},
			want: append(append([]string{}, groups...), grammarAnchors...),
		},
		{
			name: "markdown",
			args: []string{"--format", "md"},
			want: append(append([]string{"# ", "###"}, groups...), grammarAnchors...),
		},
		{
			name:    "unknown format errors",
			args:    []string{"--format", "xml"},
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			var buf bytes.Buffer
			err := stepsCmd(tt.args, &buf)
			if (err != nil) != tt.wantErr {
				t.Fatalf("err = %v, wantErr = %v", err, tt.wantErr)
			}
			if tt.wantErr {
				if !strings.Contains(err.Error(), "xml") {
					t.Errorf("error should name the offending format; got %q", err)
				}
				return
			}
			out := buf.String()
			for _, w := range tt.want {
				if !strings.Contains(out, w) {
					t.Errorf("output missing %q", w)
				}
			}
			// Every registered step pattern must appear verbatim — the reference is
			// complete, not a curated subset.
			for _, d := range steps.StepDocs() {
				if !strings.Contains(out, d.Pattern) {
					t.Errorf("output missing step pattern %q", d.Pattern)
				}
			}
		})
	}
}

// TestStepsTextGrammarHasFanoutQuantifiers proves the text grammar's Quantifiers
// section lists the two fan-out (parent/child) forms, which ARE registered steps
// (`…has at least/exactly N children matching …`). The unique grammar labels
// "fan-out lower bound"/"fan-out exact count" live only in the grammar section, so
// this asserts the Quantifiers block specifically, not the step table.
func TestStepsTextGrammarHasFanoutQuantifiers(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	if err := stepsCmd(nil, &buf); err != nil { // nil args → default text format
		t.Fatalf("stepsCmd text: %v", err)
	}
	out := buf.String()
	for _, want := range []string{"fan-out lower bound", "fan-out exact count"} {
		if !strings.Contains(out, want) {
			t.Errorf("steps text grammar missing fan-out quantifier %q", want)
		}
	}
}

// TestStepsCmdWritesFile covers the -o path the go:generate directive uses: the
// file written must be byte-identical to what the command streams to stdout.
func TestStepsCmdWritesFile(t *testing.T) {
	t.Parallel()

	var stdoutBuf bytes.Buffer
	if err := stepsCmd([]string{"--format", "md"}, &stdoutBuf); err != nil {
		t.Fatalf("stepsCmd stdout: %v", err)
	}

	dst := filepath.Join(t.TempDir(), "steps.md")
	if err := stepsCmd([]string{"--format", "md", "-o", dst}, &bytes.Buffer{}); err != nil {
		t.Fatalf("stepsCmd -o: %v", err)
	}
	got, err := os.ReadFile(dst)
	if err != nil {
		t.Fatalf("read %s: %v", dst, err)
	}
	if string(got) != stdoutBuf.String() {
		t.Errorf("-o file (%d bytes) differs from stdout (%d bytes)", len(got), stdoutBuf.Len())
	}
}
