package main

//go:generate go run . steps --format md -o ../../docs/steps.md

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/thetonymaster/mentat/internal/steps"
)

// stepsCmd renders the step reference to stdout (or a file) in the requested
// format. It is a pure seam — flag parsing plus rendering, no os.Exit — so tests
// drive it directly; main() maps its error to an exit code. The Markdown form is
// the single generator behind the committed docs/steps.md (see the go:generate
// directive above): `go generate ./...` rewrites that file, and a regeneration
// test asserts it stays byte-identical, so the reference can never drift.
func stepsCmd(args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("steps", flag.ContinueOnError)
	fs.SetOutput(stdout)
	format := fs.String("format", "text", "reference format: text (human-readable, the default) or md (Markdown — the committed docs/steps.md)")
	out := fs.String("o", "", "write the reference to this file instead of stdout")
	if err := fs.Parse(args); err != nil {
		return err
	}

	var doc string
	switch *format {
	case "text":
		doc = renderStepsText()
	case "md":
		doc = renderStepsMarkdown()
	default:
		return fmt.Errorf("steps: unknown --format %q (want text or md)", *format)
	}

	if *out != "" {
		if err := os.WriteFile(*out, []byte(doc), 0o644); err != nil {
			return fmt.Errorf("steps: writing %s: %w", *out, err)
		}
		return nil
	}
	if _, err := io.WriteString(stdout, doc); err != nil {
		return fmt.Errorf("steps: writing output: %w", err)
	}
	return nil
}

// renderStepsMarkdown builds the Markdown reference: an intro, the grouped step
// table (from steps.StepDocs — the same rows the suite registers), and the
// cross-cutting grammar. Iteration is deterministic (table order; one heading per
// contiguous group), so the output is byte-stable and safe to commit.
func renderStepsMarkdown() string {
	var b strings.Builder
	b.WriteString("# Mentat step reference\n\n")
	b.WriteString("<!-- Code-generated by `go generate ./...` (cmd/mentat/steps_cmd.go).\n")
	b.WriteString("     Steps come from internal/steps/metadata.go; the grammar from\n")
	b.WriteString("     internal/comparator and internal/cel. DO NOT EDIT BY HAND. -->\n\n")
	b.WriteString(stepsIntro)
	b.WriteString("\n## Steps\n\n")

	group := ""
	for _, d := range steps.StepDocs() {
		if d.Group != group {
			fmt.Fprintf(&b, "### %s\n\n", d.Group)
			group = d.Group
		}
		fmt.Fprintf(&b, "#### `%s`\n\n", d.Pattern)
		b.WriteString(d.Summary)
		b.WriteString("\n\n```gherkin\n")
		b.WriteString(d.Example)
		b.WriteString("\n```\n\n")
	}

	b.WriteString(strings.ReplaceAll(grammarMarkdown, "@BT@", "`"))
	return b.String()
}

// renderStepsText builds the plain-text reference for a terminal: the grouped
// step table plus the same grammar, without Markdown scaffolding.
func renderStepsText() string {
	var b strings.Builder
	b.WriteString("MENTAT STEP REFERENCE\n\n")
	b.WriteString("Every registered Gherkin step, grouped by concern, then the shared grammar.\n")
	b.WriteString("Regenerate the Markdown reference (docs/steps.md) with `go generate ./...`.\n\n")
	b.WriteString("STEPS\n")

	group := ""
	for _, d := range steps.StepDocs() {
		if d.Group != group {
			fmt.Fprintf(&b, "\n%s\n%s\n", d.Group, strings.Repeat("-", len(d.Group)))
			group = d.Group
		}
		fmt.Fprintf(&b, "  %s\n", d.Pattern)
		fmt.Fprintf(&b, "      %s\n", d.Summary)
		b.WriteString("      e.g.\n")
		for _, line := range strings.Split(d.Example, "\n") {
			fmt.Fprintf(&b, "        %s\n", line)
		}
		b.WriteString("\n")
	}

	b.WriteString(textGrammar)
	return b.String()
}

// stepsIntro is the Markdown lede.
const stepsIntro = "Mentat scenarios are written in Gherkin. This page is the generated reference\n" +
	"for every registered step, grouped by concern, followed by the cross-cutting\n" +
	"grammar shared across steps: selectors, quantifiers, ordinals, and the CEL\n" +
	"variables available to `the run satisfies` and `the runs satisfy`.\n"

// grammarMarkdown is the cross-cutting grammar in Markdown. It is a raw string
// (so the tables and quotes stay readable), and @BT@ stands in for a backtick —
// raw string literals cannot contain one — replaced at render time. Every fact
// here is transcribed from a single code definition point: selectors from
// internal/comparator/shape_selector.go (+ the trace.Status*/Kind* constants),
// ordinals from internal/comparator/result_span.go and steps.parseSpanSpec,
// quantifiers from the shape/sequence step patterns, and the CEL variables from
// internal/cel/cel.go (single-run) and internal/cel/aggregate.go +
// internal/comparator/aggregate_cel.go (aggregate).
const grammarMarkdown = `## Grammar

Beyond the per-step patterns above, several steps share a small cross-cutting
grammar. Each piece below is generated from its single definition point in code.

### Selectors

A **selector** is a quoted, comma-separated conjunction of @BT@key=value@BT@
predicates a span must satisfy — every predicate is AND-ed with exact string
equality. Whitespace around commas and @BT@=@BT@ is trimmed, and each clause
splits on its first @BT@=@BT@ so a value may itself contain @BT@=@BT@.

Three keys are reserved and read intrinsic span fields; any other key is a
span-attribute lookup (a missing attribute is a non-match, not an error):

| key | matches | example |
| --- | --- | --- |
| @BT@span.name@BT@ | the span name | @BT@span.name=execute_tool@BT@ |
| @BT@span.status@BT@ | the span status — one of @BT@Unset@BT@, @BT@Ok@BT@, @BT@Error@BT@ | @BT@span.status=Error@BT@ |
| @BT@span.kind@BT@ | the OTLP span kind — one of @BT@SPAN_KIND_INTERNAL@BT@, @BT@SPAN_KIND_SERVER@BT@, @BT@SPAN_KIND_CLIENT@BT@, @BT@SPAN_KIND_PRODUCER@BT@, @BT@SPAN_KIND_CONSUMER@BT@ | @BT@span.kind=SPAN_KIND_SERVER@BT@ |
| any other key | the span attribute of that name | @BT@service.name=billing@BT@, @BT@gen_ai.operation.name=execute_tool@BT@ |

An empty selector, a predicate without @BT@=@BT@, an empty key or value, or an
unknown @BT@span.*@BT@ key or reserved value is a hard authoring error — never a
silently-green match.

### Quantifiers

Shape and sequence steps bound *how many* spans or calls match:

| phrase | meaning |
| --- | --- |
| @BT@a span matching "…" exists@BT@ | at least one match |
| @BT@no span matching "…" exists@BT@ | zero matches (never) |
| @BT@at least N spans match "…"@BT@ | N or more matches |
| @BT@exactly N spans match "…"@BT@ | exactly N matches |
| @BT@the tool "…" is called at most N times@BT@ | at most N calls |
| @BT@the tool "…" is never called@BT@ | zero calls (never) |
| @BT@a span … has at least N children matching "…"@BT@ | fan-out lower bound |
| @BT@a span … has exactly N children matching "…"@BT@ | fan-out exact count |

### Ordinals

The tool-result and span-attribute steps (@BT@the result of … tool "X"@BT@,
@BT@attribute "…" of … span matching "…"@BT@) take an **ordinal** picking which
matching span — in start-time order — supplies the value. With no ordinal the
selector must match exactly one span, otherwise it is a hard error.

| ordinal | picks |
| --- | --- |
| *(none)* | the sole match; error if zero or more than one match |
| @BT@the first@BT@ | the earliest match |
| @BT@the last@BT@ | the latest match |
| @BT@the Nth@BT@ (@BT@the 1st@BT@, @BT@the 2nd@BT@, …) | the Nth match, 1-based; out of range is an error |
| @BT@every@BT@ | every match must satisfy (AND) |
| @BT@any@BT@ | at least one match must satisfy (OR) |

### CEL variables

Two steps evaluate a boolean CEL expression:

- @BT@the run satisfies "<expr>"@BT@ — over a single run.
- @BT@the runs satisfy "<expr>"@BT@ — over the @BT@runs@BT@ list of a @BT@@runs(N)@BT@ scenario.

**Single-run variables** (@BT@the run satisfies@BT@). Only the variables an
expression references are bound; the trace-derived ones require a resolved trace.

| variable | CEL type | value |
| --- | --- | --- |
| @BT@status@BT@ | int | response / boundary status code |
| @BT@exitCode@BT@ | int | process exit code |
| @BT@body@BT@ | dyn | response body parsed as JSON (bound only when referenced) |
| @BT@bodyText@BT@ | string | raw response body |
| @BT@answer@BT@ | string | extracted answer text |
| @BT@tokens@BT@ | int | total tokens across the trace |
| @BT@cost@BT@ | double | total cost in USD, via the pricing table |
| @BT@latencyMs@BT@ | int | wall-clock envelope in milliseconds |
| @BT@errors@BT@ | int | number of ERROR-status spans |
| @BT@tools@BT@ | list(string) | tool-call names, in call order |
| @BT@services@BT@ | list(string) | service names, in call order |

**Aggregate binding** (@BT@the runs satisfy@BT@). @BT@runs@BT@ is a list with one
record per run; each record carries @BT@runId@BT@ (string), @BT@failed@BT@ (bool),
@BT@failureKind@BT@ (string), @BT@status@BT@ (int), @BT@exitCode@BT@ (int),
@BT@bodyText@BT@ (string), @BT@answer@BT@ (string), @BT@tokens@BT@ (int),
@BT@cost@BT@ (double), @BT@errors@BT@ (int), @BT@latencyMs@BT@ (int),
@BT@tools@BT@ (list(string)), and @BT@services@BT@ (list(string)).

Alongside CEL's built-in list macros (@BT@all@BT@, @BT@exists@BT@, @BT@filter@BT@,
@BT@map@BT@, @BT@size@BT@), these aggregate macros reduce a projected metric
across the sample, each called as @BT@macro(r, r.<field>)@BT@ (e.g.
@BT@mean(r, r.latencyMs) < 800@BT@): @BT@count@BT@, @BT@rate@BT@, @BT@sum@BT@,
@BT@mean@BT@, @BT@min@BT@, @BT@max@BT@, @BT@stddev@BT@, @BT@p50@BT@, @BT@p95@BT@,
@BT@p99@BT@.
`

// textGrammar is the plain-text rendering of the same grammar (no backticks, no
// tables), grounded in the same code definition points as grammarMarkdown.
const textGrammar = `GRAMMAR

Selectors
  A selector is a quoted, comma-separated conjunction of key=value predicates a
  span must satisfy (AND-ed, exact string equality). Reserved keys read intrinsic
  fields; any other key is a span-attribute lookup:
    span.name    the span name                    e.g. span.name=execute_tool
    span.status  one of Unset, Ok, Error          e.g. span.status=Error
    span.kind    SPAN_KIND_INTERNAL | _SERVER | _CLIENT | _PRODUCER | _CONSUMER
    <attribute>  the span attribute of that name  e.g. service.name=billing,
                 gen_ai.operation.name=execute_tool
  An empty selector, a missing '=', an empty key/value, or an unknown span.* key
  or reserved value is a hard authoring error.

Quantifiers
  a span matching "..." exists              at least one match
  no span matching "..." exists             zero matches (never)
  at least N spans match "..."              N or more matches
  exactly N spans match "..."               exactly N matches
  the tool "..." is called at most N times  at most N calls
  the tool "..." is never called            zero calls (never)
  a span "..." has at least N children matching "..."  fan-out lower bound
  a span "..." has exactly N children matching "..."   fan-out exact count

Ordinals (tool-result and span-attribute steps; spans ordered by start time)
  (none)      the sole match; error if zero or more than one match
  the first   the earliest match
  the last    the latest match
  the Nth     the Nth match, 1-based (the 1st, the 2nd, ...); out of range errors
  every       every match must satisfy (AND)
  any         at least one match must satisfy (OR)

CEL variables
  the run satisfies "<expr>"   single-run boolean expression.
  the runs satisfy "<expr>"    boolean over the runs list of a @runs(N) scenario.

  Single-run variables (bound only when referenced; trace vars need a trace):
    status(int) exitCode(int) body(dyn) bodyText(string) answer(string)
    tokens(int) cost(double) latencyMs(int) errors(int)
    tools(list) services(list)
  Aggregate records (one per run in runs): runId failed failureKind status
    exitCode bodyText answer tokens cost errors latencyMs tools services
  Aggregate macros: count rate sum mean min max stddev p50 p95 p99
    called as macro(r, r.<field>), e.g. mean(r, r.latencyMs) < 800.
`
